# Generated by Django 4.1.7 on 2023-06-23 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='images',
            field=models.ImageField(blank=True, upload_to='categories/%Y/%m/%d', verbose_name='Categories Photo'),
        ),
    ]
